apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/sys-apps/helm/cert-manager/values.yaml
    - repoURL: https://github.com/vietvite/infra-cicd-test.git
      targetRevision: main
      ref: values
  destination:
    name: "in-cluster"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
