apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.0
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/argocd/sys-apps/helm/ingress-nginx/values.yaml
    - repoURL: https://github.com/vietvite/infra-cicd-test.git
      targetRevision: main
      ref: values
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
