apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietvite/infra-cicd-test.git
    targetRevision: main
    path: argocd/ms-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true