{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pyapp.fullname" . }}
  labels:
    {{- include "pyapp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "pyapp.fullname" $ }}
                port:
                  {{- if typeIs "string" $.Values.service.port }}
                  name: {{ $.Values.service.port }}
                  {{- else }}
                  number: {{ $.Values.service.port | default 80 }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
