image:
  repository: 174084228657.dkr.ecr.us-east-1.amazonaws.com/pyapp
  tag: "a3fbaa885bfa3daee15d12aface169e1021d8155"
ingress:
  enabled: true
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
service:
  port: 3000
livenessProbe:
  httpGet:
    path: /healthcheck
    port: http
readinessProbe:
  httpGet:
    path: /healthcheck
    port: http
startupProbe:
  httpGet:
    path: /healthcheck
    port: http
  failureThreshold: 3
  periodSeconds: 10