image:
  repository: 174084228657.dkr.ecr.us-east-1.amazonaws.com/pyapp
  tag: "10e29deced3fc5a042a58f66640d98eb0f3e358e"

ingress:
  enabled: true
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

service:
  port: 3000

livenessProbe:
  httpGet:
    path: /healthcheck
    port: http
readinessProbe:
  httpGet:
    path: /healthcheck
    port: http