image:
  repository: 174084228657.dkr.ecr.us-east-1.amazonaws.com/pyapp
  tag: "aec840c7b49bbf621afd2c43723eb2a3d2cd0769"
ingress:
  enabled: true
  hosts:
    - host: a87bdb64f6b73475e8806f382439b1d4-34798d1562ae7b52.elb.us-east-1.amazonaws.com
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
service:
  port: 3000
livenessProbe:
  httpGet:
    path: /healthcheck
    port: http
readinessProbe:
  httpGet:
    path: /healthcheck
    port: http
startupProbe:
  httpGet:
    path: /healthcheck
    port: http
  failureThreshold: 3
  periodSeconds: 10
